bootstrap-node:
  - enr:-LG4QPzyTPZf29D7YU2uW13UX-1x1t3SHithTcSKHtQfuDW6Z4qFqZu2Seh20nbrnZLwunandcpIlp4enRlgJ4VpXuqGAYfLcS4Lh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCAwONDLxwAAP__________gmlkgnY0gmlwhKwVQAyJc2VjcDI1NmsxoQMTpBSbzkZqJlPv3liorc_c3CzWIBJfLNIpJctzFVcOv4N1ZHCCD6A

rpc-host: 0.0.0.0
monitoring-host: 0.0.0.0
grpc-gateway-host: 0.0.0.0

