version: '3.3'
services:
  agora-scan-explorer:
    image: bosagora/agora-scan:v2.0.0
    container_name: agora-scan-explorer
    ports:
      - "3333:3333"
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../chain/node1/el:/el
      - ../config/cl:/config
      - ../config/scan:/app/config
    command: sh -c "/app/explorer --config /app/config/default.config.yml"
    networks:
      - bosagora_network

  agora-scan-statistics:
    image: bosagora/agora-scan:v2.0.0
    container_name: agora-scan-statistics
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../config/cl:/config
      - ../config/scan:/app/config
    command: sh -c "/app/statistics --config /app/config/default.config.yml"
    networks:
      - bosagora_network

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true
